# Generated by Django 3.2.8 on 2022-03-02 14:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import kgis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdppum', models.CharField(max_length=2)),
                ('namobj', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=250, null=True)),
                ('kdpbps', models.CharField(max_length=2, null=True)),
                ('fcode', models.CharField(max_length=50, null=True)),
                ('luaswh', models.FloatField()),
                ('uupp', models.CharField(max_length=50, null=True)),
                ('srs_id', models.CharField(max_length=50, null=True)),
                ('lcode', models.CharField(max_length=50)),
                ('metadata', models.CharField(max_length=50, null=True)),
                ('kdebps', models.CharField(max_length=50, null=True)),
                ('kdepum', models.CharField(max_length=50, null=True)),
                ('kdcbps', models.CharField(max_length=50, null=True)),
                ('kdcpum', models.CharField(max_length=50, null=True)),
                ('kdbbps', models.CharField(max_length=50, null=True)),
                ('kdbpum', models.CharField(max_length=50, null=True)),
                ('wadmkd', models.CharField(max_length=50, null=True)),
                ('wiadkd', models.CharField(max_length=50, null=True)),
                ('wadmkc', models.CharField(max_length=50, null=True)),
                ('wiadkc', models.CharField(max_length=50, null=True)),
                ('wadmkk', models.CharField(max_length=50, null=True)),
                ('wiadkk', models.CharField(max_length=50, null=True)),
                ('wadmpr', models.CharField(max_length=50, null=True)),
                ('wiadpr', models.CharField(max_length=50, null=True)),
                ('tipadm', models.BigIntegerField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Perangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nperangkat', models.CharField(max_length=50, verbose_name='Nama Perangkat')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu', models.FloatField(verbose_name='Suhu Ruangan')),
                ('muka_air', models.FloatField(verbose_name='Ketinggian Muka Air')),
                ('kelembapan', models.FloatField(verbose_name='Kelembapan Udara')),
                ('tegangan', models.FloatField(verbose_name='Tegangan Baterai Perangkat')),
                ('foto', models.FileField(upload_to=kgis.models.fotodir, verbose_name='Foto Kamera Perangkat')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp Server')),
                ('timestamp2', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp Perangkat')),
                ('latlong', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Lokasi Perangkat')),
                ('perangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgis.perangkat')),
            ],
        ),
    ]
